parser: "@typescript-eslint/parser"
parserOptions:
  project: ["./tsconfig.json"]
  tsconfigRootDir: "./"
  ecmaFeatures:
    jsx: true
root: true
plugins:
  - "@typescript-eslint"
  - react
  - import
  - react-hooks
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/eslint-recommended
  - plugin:@typescript-eslint/recommended
  - plugin:react/recommended
  - plugin:import/errors
  - plugin:import/warnings
  - plugin:import/typescript
  - plugin:react-hooks/recommended
rules:
  react/jsx-uses-react: "off"
  react/jsx-uses-vars: "error"
  react/react-in-jsx-scope: "off"
  react/prop-types: "off" # Disable prop-types rule, as we are using TypeScript for type checking, always complains about className prop
  import/no-named-as-default-member: "off" # Disable React named import, specific warning for shadcn components
  react/no-unescaped-entities: "off" # Disable rule for unescaped entities like ', ", <, >, etc.
settings:
  react:
    version: "detect"
  import/resolver:
    typescript:
      alwaysTryTypes: true
      project: "./tsconfig.json"
env:
  node: true
  browser: true
